# The URL the site will be built for
base_url = "https://garden.badpacket.in"
generate_rss = true
compile_sass = true
feed_filename = "rss.xml"

title = "Moabiter Stadtgarten"
description = "All the neem that's fit to plant."

taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]

[extra]
author = "Dan"
clean_blog_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/contact", name = "Contact"}
]
clean_blog_social = [
    {url = "$BASE_URL/rss.xml", icon="fas fa-rss"}
]
